ALTER TABLE verification_requests
  ADD COLUMN IF NOT EXISTS id_type VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS org_contact VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS proof_image_path VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS reason TEXT NULL;
